name: Docker Image CI

on:
  push:
    branches:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }}-arm64
          platforms: linux/arm64
          push: true

      - name: Build and Push amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }}-amd64
          platforms: linux/amd64
          push: true

      - name: Create and Push manifest
        run: |
          docker manifest create ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }} \
            ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }}-amd64 \
            ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }}-arm64
          docker manifest push ghcr.io/tech1ndex/caddy-cloudflare:${{ github.sha }}